[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo-net = "0.6.0"
serde = "1.0.219"
serde_json = "1.0.140"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"]}
